# Generated by Django 6.0.7 on 2026-08-04 18:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="profile_image",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),

        migrations.RunSQL(
            sql=[
                """
                CREATE UNIQUE INDEX accounts_user_password_reset_token_unique
                ON accounts_user (password_reset_token)
                """,
                """
                CREATE UNIQUE INDEX accounts_user_verification_token_unique
                ON accounts_user (verification_token)
                """,
            ],
            reverse_sql=[
                """
                DROP INDEX accounts_user_password_reset_token_unique
                ON accounts_user
                """,
                """
                DROP INDEX accounts_user_verification_token_unique
                ON accounts_user
                """,
            ],
        ),
    ]