# Generated by Django 6.0.7 on 2026-08-10 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', '-date', '-id'], name='expense_exp_user_id_543cb4_idx'),
        ),
    ]
