# Generated by Django 6.0.7 on 2026-08-10 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', '-date', '-id'], name='income_inco_user_id_c4e963_idx'),
        ),
    ]
